### ISSUE TITLE
What iOS versions are currently supported?

### ISSUE THREAD

**Issue by nateraw** [shiehn/runes_client#1]
Hi there! :) This project looks incredible and I'd love to play with it.

I just downloaded the installer from [dawnet.tools](https://dawnet.tools/) and it said "DAWNetInstaller can’t be installed on this computer". I assume this is an issue with my super outdated iOS (Big Sur, 11.5.2), which I realize is probably unrealistic to ask for support for 😅. I'm on a MacBook Pro (16-inch, 2019).

What version(s) of iOS are supported? Happy to test on my non-M1 machine so we know it works for others too.

Thank you!!

**Comment by shiehn** [comment]
@nateraw I'm going to pick up an older Mac tonight for testing Big Sur.  However, I did blindly cut a universal binary build.  I have no idea if it will work until later today, but feel free to try it: https://storage.googleapis.com/docs-assets/DAWNetInstaller_v0_4_0_universal.zip

**Comment by shiehn** [comment]
OK, there is a new build on the website.  I just seen it work on Big Sur + Intel.  Thanks for reporting the issue.
